[package]
name = "storage_reloaded"
version = "0.2.0"
authors = ["Sematre <Sematre@gmx.de>"]
edition = "2018"

[dependencies]
actix-web   = { version = "3" }
actix-files = "0.4"
serde       = { version = "1.0", features = ["derive"] }
serde_json  = "1.0"
