use std::collections::HashMap;

use actix_web::{error, web, HttpRequest, HttpResponse};
use sqlx::{MySqlPool, Row};

use crate::collection;
use crate::models::{AuthedUser, Database};
use crate::web_handlers::get_param;

#[actix_web::get("/databases")]
async fn get_databases(pool: web::Data<MySqlPool>, _user: AuthedUser) -> actix_web::Result<web::Json<Vec<Database>>> {
    let databases = sqlx::query_as::<_, Database>("SELECT * FROM item_databases").fetch_all(pool.as_ref()).await.unwrap();
    Ok(web::Json(databases))
}

#[actix_web::get("/database/{database_id}")]
async fn get_database(pool: web::Data<MySqlPool>, _user: AuthedUser, req: HttpRequest) -> actix_web::Result<web::Json<Database>> {
    let database_id: u64 = get_param(&req, "database_id", "database id must be a number!")?;

    // Query for the object and auto convert it.
    let query: Result<Database, sqlx::Error> = sqlx::query_as::<_, Database>("SELECT * FROM item_databases WHERE id = ?")
        .bind(database_id)
        .fetch_one(pool.as_ref())
        .await;

    // Check if the query was successful and return the database object,
    // if the database could not be found, set the status code to 404.
    // Should a different kind of error occur, return an Internal Server Error (code: 500).
    match query {
        Ok(database) => Ok(web::Json(database)),
        Err(error) => Err(match error {
            sqlx::Error::RowNotFound => error::ErrorNotFound("database not found!"),
            _ => error::ErrorInternalServerError(error),
        }),
    }
}

#[rustfmt::skip]
#[actix_web::put("/database")]
async fn put_database(pool: web::Data<MySqlPool>, _user: AuthedUser, database: web::Json<Database>) -> actix_web::Result<HttpResponse> {
    if database.id != 0 {
        return Err(error::ErrorBadRequest("database id must be 0!"));
    }

    // We need to make a transaction here because we want to make 2 queries that relate to each other.
    let mut tx = pool.as_ref().begin().await.map_err(error::ErrorInternalServerError)?;

    // First insert the object into the sql table...
    let insertion_query: Result<sqlx::mysql::MySqlQueryResult, sqlx::Error> = sqlx::query("INSERT INTO item_databases (name) VALUES (?)")
        .bind(&database.name)
        .execute(&mut tx)
        .await;

    // ...then make sure it didn't fail.
    if let Err(error) = insertion_query {
        return Err(match error {
            sqlx::Error::Database(db_error) if db_error.message().starts_with("Duplicate entry") => error::ErrorConflict("there already is a database with this name!"),
            _ => error::ErrorInternalServerError(error),
        });
    }

    // After that we need to get the autogenerated id from the table.
    let selection_query: Result<sqlx::mysql::MySqlRow, sqlx::Error> = sqlx::query("SELECT LAST_INSERT_ID()").fetch_one(&mut tx).await;

    // If we encounter an error then return status 500,
    // if not, extract the id from the query.
    let database_id: u64 = selection_query.map_err(error::ErrorInternalServerError)?.try_get(0).unwrap();

    // Finally commit the changes to make them permanent
    tx.commit().await.map_err(error::ErrorInternalServerError)?;
    Ok(HttpResponse::Created().json::<HashMap<&str, u64>>(collection! {
        "database_id" => database_id
    }))
}

#[actix_web::post("/database/{database_id}")]
async fn update_database(pool: web::Data<MySqlPool>, _user: AuthedUser, req: HttpRequest, database: web::Json<Database>) -> actix_web::Result<HttpResponse> {
    let database_id: u64 = get_param(&req, "database_id", "database id must be a number!")?;
    if database.id != database_id {
        return Err(error::ErrorBadRequest("the database ids don't match!"));
    }

    // Update the object in the sql table...
    let query: Result<sqlx::mysql::MySqlQueryResult, sqlx::Error> = sqlx::query("UPDATE item_databases SET name = ? WHERE id = ?")
        .bind(&database.name)
        .bind(&database.id)
        .execute(pool.as_ref())
        .await;

    // ...then make sure it didn't fail.
    let result = match query {
        Ok(result) => result,
        Err(error) => {
            return Err(match error {
                sqlx::Error::Database(db_error) if db_error.message().starts_with("Duplicate entry") => error::ErrorConflict("there already is a database with this name!"),
                _ => error::ErrorInternalServerError(error),
            })
        }
    };

    // If nothing was changed, the database didn't even exist!
    if result.rows_affected() == 0 {
        return Err(error::ErrorNotFound("database not found!"));
    }

    Ok(HttpResponse::Ok().finish())
}

#[actix_web::delete("/database/{database_id}")]
async fn delete_database(pool: web::Data<MySqlPool>, _user: AuthedUser, req: HttpRequest) -> actix_web::Result<HttpResponse> {
    let database_id: u64 = get_param(&req, "database_id", "database id must be a number!")?;

    let query: Result<sqlx::mysql::MySqlQueryResult, sqlx::Error> = sqlx::query("DELETE FROM item_databases WHERE id = ?").bind(&database_id).execute(pool.as_ref()).await;

    // Get the query result or else return error 500.
    let query_result = query.map_err(error::ErrorInternalServerError)?;

    // If nothing was deleted, the database didn't even exist!
    if query_result.rows_affected() == 0 {
        return Err(error::ErrorNotFound("database not found!"));
    }

    Ok(HttpResponse::Ok().finish())
}
