name: Rust CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: build (${{ matrix.job.common }})
    strategy:
      matrix:
        job:
        - { name: linux-x86_64,   common: Linux x86 (64-Bit),   target: x86_64-unknown-linux-gnu,      output: storagereloaded     }
        - { name: linux-x86,      common: Linux x86 (32-Bit),   target: i686-unknown-linux-gnu,        output: storagereloaded     }
        - { name: linux-aarch64,  common: Linux ARM64,          target: aarch64-unknown-linux-gnu,     output: storagereloaded     }
        - { name: linux-armv7,    common: Linux ARMv7,          target: armv7-unknown-linux-gnueabihf, output: storagereloaded     }
        - { name: linux-arm,      common: Linux ARM,            target: arm-unknown-linux-gnueabihf,   output: storagereloaded     }
        - { name: windows-x86_64, common: Windows x86 (64-Bit), target: x86_64-pc-windows-gnu,         output: storagereloaded.exe }
        - { name: windows-x86,    common: Windows x86 (32-Bit), target: i686-pc-windows-gnu,           output: storagereloaded.exe }
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.job.target }}
        override: true
    - name: Setup cache
      uses: Swatinem/rust-cache@v1
      with:
        key: ${{ matrix.job.name }}
    - name: Build with Cargo
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --release --target=${{ matrix.job.target }}
    - name: Upload Binary
      uses: actions/upload-artifact@v2
      with:
        name: "Build: ${{ matrix.job.common }}"
        path: target/${{ matrix.job.target }}/release/${{ matrix.job.output }}

  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Setup cache
      uses: Swatinem/rust-cache@v1
    - name: Run cargo check
      uses: actions-rs/cargo@v1
      with:
        command: check

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Setup cache
      uses: Swatinem/rust-cache@v1
    - name: Run cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test

  lints:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: rustfmt, clippy
    - name: Setup cache
      uses: Swatinem/rust-cache@v1
    - name: Install typos
      uses: actions-rs/install@v0.1
      with:
        crate: typos-cli
        version: latest
        use-tool-cache: true
    - name: Run cargo clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings
    - name: Run typos
      run: typos
