name: Rust CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: build (${{ matrix.common }})
    strategy:
      matrix:
        name:
        - linux-x86_64
        - linux-x86
        - linux-aarch64
        - linux-armv7
        - linux-arm
        - windows-x86_64
        - windows-x86

        include:
        - name: linux-x86_64
          common: Linux x86 (64-Bit)
          target: x86_64-unknown-linux-gnu
        - name: linux-x86
          common: Linux x86 (32-Bit)
          target: i686-unknown-linux-gnu
        - name: linux-aarch64
          common: Linux ARM64
          target: aarch64-unknown-linux-gnu
        - name: linux-armv7
          common: Linux ARMv7
          target: armv7-unknown-linux-gnueabihf
        - name: linux-arm
          common: Linux ARM
          target: arm-unknown-linux-gnueabihf
        - name: windows-x86_64
          common: Windows x86 (64-Bit)
          target: x86_64-pc-windows-gnu
        - name: windows-x86
          common: Windows x86 (32-Bit)
          target: i686-pc-windows-gnu
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        override: true
    - uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --release --target=${{ matrix.target }}

  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Run cargo check
      uses: actions-rs/cargo@v1
      with:
        command: check

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Run cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test

  lints:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: rustfmt
    - name: Run cargo fmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check
